[project]
name = "jira-time-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prompt-toolkit>=3.0.51",
    "readchar>=4.2.1",
    "requests>=2.32.3",
]
